# Generated by Django 3.1.2 on 2020-12-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('emission_date', models.DateField(auto_now_add=True)),
                ('customer_name', models.TextField()),
                ('customer_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Linea_de_Factura',
            fields=[
                ('id_line', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('unit_prize', models.FloatField()),
                ('unit_total', models.IntegerField()),
                ('facture_line', models.ForeignKey(default='DEF', on_delete=django.db.models.deletion.PROTECT, related_name='linea', to='factura.factura')),
            ],
        ),
    ]
